[config]

[target]
exclude = []
target_require_empty = false

[target.windows]
directory = '~/AppData/Roaming/nushell'

[target.linux]
directory = '~/.config/nushell'

[dependencies.simple]
local = []
system = []
